indi-duino/devices/CMakeLists.txt
indi-duino/devices/Firmwares/indiduinoMETEO/indiduinoMETEO.ino
indi-duino/devices/meteostationSQM_sk.xml
indi-duino/indi_duino.xml.cmake

OK, got it right now, I hope :-). It's a more involved process than I thought and getting older doesn't make it easier but I thought I could contribute so, here it is, sorry for all the trouble and thanks for your comprehension.
All modified and required files should be there. I tested the modifications, even rebuilt INDI from a fresh download, ran KStars/EKOS/INDI and there was no problem. 
The process is simple. After flashing the Arduino meteo station firmware with your specific sensors selection, in INDI you either choose, in the Weather tab of the Profile Editor, "Arduino MeteoStation" or "Arduino MeteoStation SQM" for either the legacy  or SQM-enhanced virtual driver. Once you start INDI and connect to the meteo station, the appropriate skeleton file will be used and the sensor …

Updated Arduino MeteoStation

---

indi-duino/CMakeLists.txt
indi-duino/add-on/meteostationWEB/html/steelGauge.html
indi-duino/add-on/meteostationWEB/meteoRRD_graph.py
indi-duino/add-on/meteostationWEB/meteoRRD_single_graph.py
indi-duino/add-on/meteostationWEB/meteoRRD_single_update.py
indi-duino/add-on/meteostationWEB/meteoRRD_updater.py
indi-duino/add-on/meteostationWEB/meteoconfig.py
indi-duino/add-on/meteostationWEB/meteostation.py
indi-duino/add-on/meteostationWEB/munin/meteoweb-humidity.py
indi-duino/add-on/meteostationWEB/munin/meteoweb-munin.py
indi-duino/add-on/meteostationWEB/munin/meteoweb-pressure.py
indi-duino/add-on/meteostationWEB/munin/meteoweb-temperature.py
indi-duino/add-on/meteostationWEB/munin/munin_meteoweb.py
indi-duino/devices/Firmwares/indiduinoMETEO/indiduinoMETEO.ino
indi-duino/devices/meteostation_sk.xml
indi-duino/indiduino.cpp

A set of minor improvements and bug fixes:
- polling period made configurable
- timeout dependent on polling interval
- parameter names synced with meteostationWEB
- munin clients added for temperature, pressure and humidity
- weather status flags changed to IPS_OK and IPS_ALERT values
- first INDI tab renamed to Main Control (INDI standard)
- separated RRD updates into single calls and library (may be used as cron jobs)

indi-duino V0.4.1 | minor improvements

---

debian/indi-gphoto/postinst

Building DEB package on plain Raspbian or Debian GNU/Linux 10 (buster)
with the following script results in error:
libgphoto2 PPA is not installed. Will enable it now...
/var/lib/dpkg/info/indi-gphoto.postinst: 21: /var/lib/dpkg/info/indi-gphoto.postinst: apt-add-repository: not found
dpkg: error processing package indi-gphoto (--install):
installed indi-gphoto package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of indi-gphoto-dbg:
indi-gphoto-dbg depends on indi-gphoto (= 2.9); however:
Package indi-gphoto is not configured yet.
dpkg: error processing package indi-gphoto-dbg (--install):
dependency problems - leaving unconfigured
Thus activate ppa:mutlaqja/libgphoto2 on Ubuntu distros only.
---------------------- …

Do not add/activate ppa:mutlaqja/libgphoto2 on non-Ubuntu distros

---

indi-limesdr/indi_limesdr_detector.cpp
indi-limesdr/indi_limesdr_detector.h
indi-rtlsdr/indi_rtlsdr_detector.cpp
indi-rtlsdr/indi_rtlsdr_detector.h

Renamed functions with guidance from radio simulator. Also ran through clang-format as the indentation was a bit all over the place.

Update RTLSDR and LIMESDR drivers to spectrograph device

---

indi-shelyak/indi_shelyakspox_spectrograph.cpp
indi-shelyak/indi_shelyakspox_spectrograph.h

Hi, 
add SKY Button disabling all lamps.
Cleaning mechanism of selection

add sky button and cleaning

---

debian/indi-duino/changelog
indi-duino/devices/Firmwares/weatherradio/config.h
indi-duino/devices/Firmwares/weatherradio/esp8266.h
indi-duino/devices/Firmwares/weatherradio/mlx90614.h
indi-duino/devices/Firmwares/weatherradio/tsl237.h
indi-duino/devices/Firmwares/weatherradio/tsl2591.h
indi-duino/devices/Firmwares/weatherradio/version.h
indi-duino/devices/Firmwares/weatherradio/weatherradio.ino
indi-duino/weatherradio.cpp
indi-duino/weatherradio.h

Next step towards independence from a raspberry connected to the USB port: added web server that displays all JSON documents (for ESP8266 boards).
Additional features:
* Support for TSL237 added
* INDI driver reacts dynamically to connected sensors (but no option to read from the web server)
* bug fixes

Weather Radio v 0.7 | Web server added

---

debian/indi-duino/changelog
indi-duino/add-on/weatherradio/bin/weatherradio.py
indi-duino/add-on/weatherradio/bin/wr_config.py
indi-duino/add-on/weatherradio/bin/wr_rrd_update.py
indi-duino/add-on/weatherradio/bin/wr_rrd_update_sensordata.py
indi-duino/add-on/weatherradio/weatherradio.conf
indi-duino/devices/Firmwares/weatherradio/config.h
indi-duino/devices/Firmwares/weatherradio/tsl237.h
indi-duino/devices/Firmwares/weatherradio/version.h
indi-duino/weatherradio.cpp

With this release it should be possible to use TSL237 as alternative to the TSL2591 for SQM measurement.
Additionally, the RRD update scripts are improved so that they do not any longer get stuck when there are connection problems or not all sensors connected.

Weatherradio V 0.9 | TSL237 updates + script robustness

---

indi-talon6/talon6.cpp

Hi,
we are making a device that speaks the Talon6 protocol and while doing so it seemed like a good opportunity to clean up a bit the driver.
This PR just removes some redundant conversions.

Talon6 cleanup

---

indi-atik/CMakeLists.txt
indi-atik/atik_ccd.cpp
indi-atik/atik_ccd.h
libatik/AtikCameras.h
libatik/CMakeLists.txt

This PR update the armhf, arm64, x86-linux and x64-linux to version 1.4.0.5, with the relevant `ArtemisCameras.h`.
Files were extracted from https://www.atik-cameras.com/wp-content/uploads/2020/05/AtikCamerasSDK_2020_05_07.zip.

Update Atik SDK to 20200507-v145.

---

debian/indi-nightscape/changelog
debian/libasi/changelog

Housekeeping - debian changelogs update

---

debian/indi-pentax/control
indi-pentax/pktriggercord_ccd.cpp
indi-pentax/pktriggercord_ccd.h

Also added extra debug statements.

Possible fix for buffer saving problems on Pentax K30 and others.

---

indi-sx/sxccdusb.cpp

A possible workaround for #156

sxccdusb 40000 bulk transfer timeout

---

indi-rpicam/mmaldriver.cpp

Also tolerate camera name "testc"

---

debian/indi-rpicam/changelog
indi-rpicam/CMakeLists.txt
indi-rpicam/mmaldriver.cpp
indi-rpicam/mmaldriver.h
indi-rpicam/pipeline.cpp
indi-rpicam/pipeline.h
indi-rpicam/raw10tobayer16pipeline.cpp
indi-rpicam/raw10tobayer16pipeline.h
indi-rpicam/rpi-crosscompile.cmake

This patch will support the older V2 Raspberry PI camera

Support for the V2 camera

---

libqhy/libqhy.spec

fxload_spec: add the Require: fxload entry for libqhy

---

debian/indi-duino/changelog
indi-duino/devices/Firmwares/weatherradio/bme280.h
indi-duino/devices/Firmwares/weatherradio/config.h
indi-duino/devices/Firmwares/weatherradio/davis_anemometer.h
indi-duino/devices/Firmwares/weatherradio/dht.h
indi-duino/devices/Firmwares/weatherradio/esp8266.h
indi-duino/devices/Firmwares/weatherradio/memory.h
indi-duino/devices/Firmwares/weatherradio/mlx90614.h
indi-duino/devices/Firmwares/weatherradio/oled.h
indi-duino/devices/Firmwares/weatherradio/tsl237.h
indi-duino/devices/Firmwares/weatherradio/tsl2591.h
indi-duino/devices/Firmwares/weatherradio/version.h
indi-duino/devices/Firmwares/weatherradio/weatherradio.ino

The new version of weather radio brings the support for a small OLED display to display sensor data. Additionally, a memory leak has been fixed.

Weatherradio V 1.8 | OLED display support + memory leak fixed

---

debian/indi-rpicam/changelog
indi-rpicam/CMakeLists.txt
indi-rpicam/FindARM.cmake
indi-rpicam/README.md
indi-rpicam/TODO
indi-rpicam/cameracontrol.cpp
indi-rpicam/cameracontrol.h
indi-rpicam/jpegpipeline.cpp
indi-rpicam/jpegpipeline.h
indi-rpicam/mmalcamera.cpp
indi-rpicam/mmalcomponent.cpp
indi-rpicam/mmaldriver.cpp
indi-rpicam/raw10tobayer16pipeline.cpp
indi-rpicam/raw10tobayer16pipeline.h
indi-rpicam/test/CMakeLists.txt
indi-rpicam/test/test_imx219.cpp
indi-rpicam/test/test_imx477.cpp

* Also supports V1 camera (omv5647 chip).
* Performance improvements, especially for the V1 and V2 camera.

indi-rpicam 1.3

---

debian/indi-rpicam/changelog
indi-rpicam/CMakeLists.txt
indi-rpicam/cameracontrol.cpp
indi-rpicam/mmalcamera.cpp
indi-rpicam/mmalcamera.h
indi-rpicam/mmalcomponent.cpp
indi-rpicam/mmalcomponent.h
indi-rpicam/mmaldriver.cpp
indi-rpicam/mmalencoder.cpp
indi-rpicam/mmalencoder.h
indi-rpicam/raw10tobayer16pipeline.cpp

* Corrected colors
* Long exposures more stable

indi-rpicam:1.4

---

indi-atik/CMakeLists.txt
indi-atik/atik_ccd.cpp
libatik/AtikCameras.h
libatik/CMakeLists.txt

PR integrating the October 2020 SDK from Atik.
Note that it also reverts the length parameter of `ArtemisCameraSpecificOptionGetData` to a pointer.

Update Atik SDK to 2020 October 19 release before test.

---

indi-dsi/dsi_ccd.cpp

This PR is a tentative fix for the unrecognised Bayer pattern of the Meade DSI Color III.

Advertise RGGB pattern on DSI Color III (tentative).

---

indi-duino/indiduino.cpp
indi-duino/indiduino.h
indi-duino/libfirmata/src/firmata.cpp

TCP connection has been tested on ESP8266 board with this firmware:
https://github.com/firmata/arduino/tree/master/examples/StandardFirmataWiFi

Enable tcp connection in indi-duino

---

indi-asi-power/CMakeLists.txt
indi-asi-power/Changelog
indi-asi-power/README.md
indi-asi-power/asipower.cpp

Minor fixes to correctly report pigpiod version number, number ports from 1-4 instead of 0-3 and ensure that a port assigned to type None is forced OFF. Update README file

indi-asi-power v0.8 

---

debian/indi-asi-power/changelog
indi-asi-power/CMakeLists.txt
indi-asi-power/Changelog
indi-asi-power/README.md
indi-asi-power/asipower.cpp
indi-asi-power/pigpiod.service.in

Ensure only one device type (None) is set On at startup.
Fix typo in README.MD

indi-asi-power v0.9 Correcty initialize device type to None

---

debian/indi-asi-power/changelog

Sorry - missed wrong formatting of changelog

indi-asi-power: Fix debian changelog formatting

---

debian/indi-asi-power/changelog
debian/indi-asi-power/control
indi-asi-power/CMakeLists.txt
indi-asi-power/Changelog
indi-asi-power/README.md
indi-asi-power/asipower.cpp

This should resolve the issue with installing on Astroberry
Also a minor fix on an error message to clarify for the user which value is in error and on return codes in ISNewSwitch

indi-asi-power Replace pigpiod package and minor message and logic fix

---

indi-asi/asi_ccd.cpp
indi-asi/asi_ccd.h

Hi!
Referring to https://github.com/indilib/indi/pull/1375
Changes:
- Remove 'IS' Functions
- Simple loader class
- Format document

ASI CCD - Remove 'IS' Functions

---

debian/indi-asi-power/changelog
indi-asi-power/CMakeLists.txt
indi-asi-power/Changelog
indi-asi-power/asipower.cpp

In ISNewSwitch and ISNewNumber ensure consistent return values

indi-asi-power v0.94 Minor fix to return codes

---

debian/indi-avalon/changelog
indi-avalon/lx200stargo.cpp
indi-avalon/lx200stargo.h
indi-avalon/lx200stargofocuser.cpp
indi-avalon/lx200stargofocuser.h

Some INDI internals changed making it necessary to adapt the Avalon driver.

Avalon StarGo V 1.12 | Updates for INDI Release 1.9

---

indi-mi/mi_ccd.cpp

@knro Please check.
Fix for https://github.com/indilib/indi-3rdparty/issues/389

Call 'gxccd_initialize' after 'gxccd_enumerate'.

---

debian/libahp-xc/control
debian/libahp-xc/libahp-xc.install
debian/libahp-xc/rules
debian/libaltaircam/rules
debian/libasi/rules
debian/libatik/rules
debian/libinovasdk/control
debian/libinovasdk/libinovasdk.install
debian/libinovasdk/rules
debian/libmallincam/rules
debian/libnncam/rules
debian/libqhy/rules
debian/libsbig/rules
debian/libstarshootg/rules
debian/libsv305/rules
debian/libtoupcam/rules

Details: https://github.com/indilib/indi-3rdparty/pull/391
- Remove DEB_DH_LINK_ARGS.
- Remove of packages that cannot be built - libahp-xc-dbg and libinovasdk-dbg
- Remove libinovasdk.install
- Remove libahp-xc.install

Fix deb packages

---

indi-ahp-correlator/indi_ahp_correlator.cpp
indi-ahp-correlator/indi_ahp_correlator.h
indi-limesdr/CMakeLists.txt
indi-limesdr/indi_limesdr.xml.cmake
indi-limesdr/indi_limesdr_receiver.cpp
indi-limesdr/indi_limesdr_receiver.h

Moved indi-limesdr into Receivers group,
Updated indi-ahp-correlator

Moved indi-limesdr into Receivers group,

---

debian/indi-playerone/changelog
indi-playerone/CMakeLists.txt
indi-playerone/ChangeLog
indi-playerone/playerone_camera_test.cpp
indi-playerone/playerone_ccd.cpp
indi-playerone/playerone_helpers.h

I’m always grateful for your help.
I forked again and reflected about all my changes.
Now there are no issues to merge.
Could you please check it?
I attached revised screen capture again.

BugFix: delete guide control in Controls tab (retry)

---

indi-asi/asi_base.cpp

The ASI driver delivers an image even if capturing has been aborted. With this fix, this will be avoided and the frame only delivered if the capture has been completed.
See discussion [here on the INDI forum](https://www.indilib.org/forum/development/10346-asi-driver-sends-image-after-abort.html).

Bug fix to avoid sending the image if capturing has been aborted

---

indi-toupbase/oem_cameras.cpp

Fix DSI IV cameras that have DDR buffer

---

indi-avalon/lx200stargo.cpp

I hope this is correct now ...

fix spelling

---

debian/indi-aok/changelog
indi-aok/CMakeLists.txt
indi-aok/ChangeLog
indi-aok/lx200aok.cpp
indi-aok/lx200aok.h

* corrected return control lights for emitting manual guide pulses
* cleaned up structure of source code
* improved parser and documentation for JSON response
* corrected pierside info message ("pointig east/west" was reversed)
* added lunar tracking mode
* adapted system speed to corresponding values of new firmware
* augmented JSON-Buffer to 256 chars
* augmented return buffer of helperfunctions to 32 chars

Driver Version 2.0: refactor and overhaul of firmware 21xxxxxx for Skywalker Teleskop Controller

---

indi-webcam/indi_webcam.cpp
indi-webcam/indi_webcam.h

https://github.com/FFmpeg/FFmpeg/blob/n5.0/doc/APIchanges#L179-L195
https://github.com/FFmpeg/FFmpeg/blob/n5.0/doc/APIchanges#L569-L572

for ffmpeg 5.0 api changes

---

indi-asi-power/asipower.cpp
indi-asi-power/asipower.h

This patch support for the ASIAIR Plus power sensor for indi-asi-power.

ASIAIR Plus power sensor support

---

debian/indi-orion-ssg3/indi-orion-ssg3.install

Add orion ssg3 udev rule to deb package

---

indi-rpicam/mmalcamera.cpp

as mentioned on indilib forums

Fix rpicam bug with 1s exposure

---

debian/indi-aagcloudwatcher-ng/changelog
indi-aagcloudwatcher-ng/CMakeLists.txt
indi-aagcloudwatcher-ng/CloudWatcherController_ng.cpp
indi-aagcloudwatcher-ng/README.txt
indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.cpp
indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.h

Added Debug Output
Handling Devices with Firmware >= 5.8 but no humidity and pressure sensor
Fixed Sensor Tab Mapping

Handling Devices with Firmware >= 5.8 but no humidity and pressure sensor

---

libatik/AtikCameras.h

This PR upgrades the Atik SDK to version 2022.07.14.1005 (Beta version).
There is an additional Beta SDK available, 2022.08.16, with a fix for Apx60, which I may upgrade to later.
It is probable 2022.07.13 fixes #382.
**2022.07.15 -  DLL v2022.07.14.1005**
- First relase containing firmware for the TE-47.
**2022.07.13 - DLL v2022.07.13.1003**
- Linux bug fix
- Fixed issue with iterating through connected udev devices.
**2022.07.06 - DLL v2022.07.06.999**
- Apx Series
- Updated the Apx26/60’s cooling algorithm so that it sits tighter on the setpoint
- TE-77
- Fixed bug that allowed the exposure speed to be set outside of the 3 available modes causing undefined behaviour.
- Debug Output
- Our debug output has now been updated to be cross platform and the location changed to the current …

Upgrade Atik SDK to 2022.07.14.1005.

---

indi-dreamfocuser/dreamfocuser.cpp
indi-dreamfocuser/dreamfocuser.h

Refactoring to use FOCUS_TEMPERATURE property.

Refactoring to use FOCUS_TEMPERATURE property.

---

debian/indi-svbony/postinst

This pull request fixes a processing omission in https://github.com/indilib/indi-3rdparty/pull/672.

Added "postinst" to delete previous driver list "indi_sv305_ccd.xml"

---

indi-beefocus/unit_tests/test_helpers.h
indi-dsi/NamedEnum.h
indi-duino/libfirmata/src/firmata.cpp

Several bug fixes that the compiler found from Fedora.

Fix fedora build

---

indi-atik/CMakeLists.txt
indi-atik/atik_ccd.cpp

- Fixed Atik One filter issue whilst using ASCOM where the previous filter position would be shown.
- TE-47 fixed intermittent issue with long exposures
- TE-47 trigger fixed
- Apx60 TriggerIn fixed.

Upgrade Atik SDK to 2022.10.21.1036.

---

debian/libsvbony/changelog
libsvbony/CMakeLists.txt

Version 1.9.7
1. Fixed the bug that SV405CC occasionally loses response(Camera firmware needs to be upgraded to v2.0.0.6)
2. Fixed the bug that SV405CC cannot set the maximum resolution
Version 1.9.8
1.Fixed the bug that SV405CC set some resolution images incorrectly
Note:
This upgrade fixes #666

Update SVBONY Camera SDK to 1.9.8 (Fixed #666)

---

indi-aagcloudwatcher-ng/CloudWatcherController_ng.cpp
indi-aagcloudwatcher-ng/CloudWatcherController_ng.h
indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.cpp
indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.h
indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng_sk.xml
indi-aagcloudwatcher-ng/main.cpp

See also https://lunaticoastro.com/lunabbs/viewtopic.php?t=444

Updated to be compatible with Firmware 5.88

---

indi-gpsd/gps_driver.cpp
indi-gpsnmea/gpsnmea_driver.cpp
indi-rtklib/rtklib_driver.cpp

This commit is linked to INDI PR
[https://github.com/indilib/indi/pull/1814](https://github.com/indilib/indi/pull/1814)

Update drivers inheriting INDI::GPS to be inline with INDI 2.0.0

---

indi-nut/indi_nut.cpp
indi-nut/indi_nut.h

Referring to: https://github.com/indilib/indi-3rdparty/issues/715

Fix indi-nut

---

indi-qhy/qhy_ccd.cpp
indi-qhy/qhy_ccd.h

Pass exposure start timestamp from GPS into SER timestamp.

Pass timestamp value into SER recorder

---

debian/indi-svbony/changelog
debian/libsvbony/changelog
indi-svbony/CMakeLists.txt
indi-svbony/svbony_ccd.cpp
indi-svbony/svbony_ccd.h
libsvbony/CMakeLists.txt

Update SVBONY SDK
* SVBONY camera SDK 1.10.2
1. Solve the problem that SV405CC soft trigger does not plot
2. Export SVBRestoreDefaultParam on Linux and MacOS
3. libSVBCameraSDK.dylib under MacOS sets rpath
* indi-svbony-ccd
Added process to initialize Camera parameters when Camera is connected.

Fix svbony sdk for some issues

---

debian/indi-aagcloudwatcher-ng/changelog
debian/indi-aok/changelog
scripts/indi-3rdparty-deb.sh

Hi,
Debian changelog date format fix for issues #755 and # 756
According to https://manpages.debian.org/testing/dpkg-dev/deb-changelog.5.en.html
Best regards

Debian changelog date format fix for issues #755 and # 756

---

indi-rpicam/raw12tobayer16pipeline.cpp

Add an optimization to process the 3 bytes of raw12 to bayer16 in one go rather than on 3 loop iterations provided there's more than 3 bytes of data in the buffer. On my system (Raspberry Pi 2), it reduces processing time for a mode-2 HQ image (2028x1520) from 2.8seconds to 0.7. This is most welcome when using it as a guide cam.
Note, some of the changes are due to formatting changes from running "astyle".

indi-rpicam: A performance optimization provided there's more than 3 bytes left to process

---

indi-eqmod/skywatcher.cpp

I noticed many responses from the mount contained none-hexadecimal characters pointing to some kind of corruption. By rejecting such responses and forcing the client to retry, no corrupt data will propagate to the higher layers.
This should improve situation as described in https://www.cloudynights.com/topic/749844-eq6-r-pro-tracking-glitch/ This will allow people with buggy decoders to use safeguards such as HA limits again.

Sanitize response eqmod/skywatcher response data

---

indi-eqmod/skywatcher.cpp
indi-eqmod/skywatcher.h

simply removing duplicate codes on the commits included in v2.0.2, re: deprecated functions

Eqmod cleanup

---

debian/indi-avalon/changelog
indi-avalon/CMakeLists.txt

Old version 1.11 was visible in the driver - fixed.

Bug fix for updated version numbers

---

indi-atik/atik_ccd.cpp

This MR accepts requests to set the cooler temperature to the same value repeatedly. The previous behaviour would return an error, which could be considered stopping the cooler by clients, while the device was still actively cooling.
Therefore, If the temperature request is higher than the current temperature by strictly more than five degrees (to allow for cooling overshoot), and the current temperature is lower than zero, this MR forces the cooler to stop and return an error.
If the temperature request is higher than the current temperature by strictly more than five degrees, and the current temperature is higher than zero, this MR retains the previous behaviour, which was to keep the cooler activated but set the temperature to zero degrees.
More warnings are now issued as well.

Atik: relax temperature control

---

libmeadecam/meadecam.c

This fixes the x86-64 Deb builds

Fix meadecam static symbols

---

indi-celestronaux/celestronaux.cpp
indi-celestronaux/celestronaux.h

guiding units fix for celestron aux

---

indi-celestronaux/celestronaux.cpp

celestron-aux bugfix: track target was not updated after manual slew

---

cmake_modules/FindINDI.cmake
indi-avalonud/CMakeLists.txt
indi-avalonud/indi_avalonud_aux.cpp
indi-avalonud/indi_avalonud_focuser.cpp
indi-avalonud/indi_avalonud_telescope.cpp
indi-weewx-json/CMakeLists.txt
indi-weewx-json/indi_weewx_json.h

Related to https://github.com/indilib/indi/pull/1970
Use system's provided json library if main indilib is built without bundling json library.

Allow using system provided json library

---

indi-asi/asi_base.cpp

In rare instances exposures fail. It seems like `ASIGetExpStatus` must be called in busy loop.

Fix rare error Exposure failed after 3 attempts.

---

debian/libsvbony/changelog
libsvbony/CMakeLists.txt

Change Log of libsvbony
* Optimizing the Long Exposure Setting of SC432M Camera
* Optimize SC432M camera software
* Solve the problem of cooling stopping briefly after the camera switches from long exposure to short exposure.
* Fixed the problem that SV905C small resolution offset does not take effect

Updated svbony camera sdk to version 1.12.6

---

indi-toupbase/indi_toupwheel.cpp
indi-toupbase/indi_toupwheel.h

* Support auto direction spinning of filter wheel.
* Add debug control.
* Initialize member variable "TargetFilter" when reconnect to device.

Toupetek AFW: support auto direction spinning and some improvement.

---

debian/indi-avalon/changelog
indi-avalon/CMakeLists.txt
indi-avalon/lx200stargo.cpp
indi-avalon/lx200stargo.h

With this feature the Avalon StarGO driver derives adaptions of the RA tracking speed from guiding pulses.

Avalon StarGO V 1.14 | auto tracking adjustment added

---

indi-aok/lx200aok.cpp
indi-asi/asi_st4.cpp
indi-avalon/lx200stargo.cpp
indi-avalonud/indi_avalonud_telescope.cpp
indi-bresserexos2/BresserExosIIGoToDriver.cpp
indi-celestronaux/CMakeLists.txt
indi-celestronaux/celestronaux.cpp
indi-eqmod/eqmodbase.cpp
indi-qhy/qhy_ccd.cpp
indi-starbook-ten/indi_starbook_ten.cpp
indi-sx/sxao.cpp

Update to compile with INDI guide interface refactor

---

indi-duino/powerbox.cpp
indi-duino/powerbox.h

Update power box to comply with INDI updated lightbox interface

Update power box to comply with INDI updated lightbox

---

debian/libsvbony/changelog
libsvbony/CMakeLists.txt

Update SVBONY SDK to 1.13.2
* Support new camera SV905C2, SV305C Pro
* Fixup ASCOM software to support SV905C2 and SV305C Pro cameras
* Fixup exposure time of SV905C2
* Optimize gain settings of SV905C2

Svbony sdk update to 1.13.2

---

debian/libsvbony/changelog
libsvbony/CMakeLists.txt

* Support new camera SV905C2, SV305C Pro
* Fixup ASCOM software to support SV905C2 and SV305C Pro cameras Fixup exposure time of SV905C2
* Optimize gain settings of SV905C2
Re-commit #1015

Update SVBONY SDK to 1.13.2

---

indi-gpio/CMakeLists.txt
indi-gpio/README.md
indi-gpio/indi_gpio.cpp
indi-gpio/indi_gpio.h
indi-playerone/playerone_base.cpp

1. Add Hardware PWM support by using sysfs
2. Add Pulse mode support for garage openers.

Add PWM and Pulse Mode support

---

indi-eqmod/align/chull/chull.c

`bool` is now a protected keyword in GCC15/C++23

fix indi-eqmod build on GCC15/C++23

---

debian/libsvbony/changelog
libsvbony/CMakeLists.txt

* Fixed the issue of long exposure image capture timeout for SV305CPRO camera
* Fixed the problem that SV305MPRO cannot be opened normally in v1.13.0 and later versions

Upgraded to SVBONY SDK vers. 1.13.4

---

libatik/AtikCameras.h
libatik/AtikDefs.h
libatik/CMakeLists.txt
libatik/sdk2libatik.sh

Update of the Atik SDK tp 2024.11.26.2038.

feat: update Atik SDK to 2024.11.26.2038.

---

debian/indi-ocs/control

Added libnova dependancy

---

debian/indi-nut/control

Adds libnutclient-dev dependancy for debian build

---

debian/indi-ocs/changelog
indi-ocs/CMakeLists.txt
indi-ocs/indi_ocs.xml.cmake
indi-ocs/ocs.cpp

Correction for missed park state and incorrect return value.

Fix for park state and typo

---

indi-toupbase/indi_toupbase.cpp
indi-toupbase/indi_toupbase.h

Migrate driver to new properties and save all possible configs in the configuration file.

Migrate driver to new INDI properties
