indilib/indi-3rdparty

- debian/indi-avalon/changelog
- indi-avalon/CMakeLists.txt
- indi-avalon/lx200stargo.cpp
- indi-avalon/lx200stargo.h
Several improvements to avoid timeouts:
* Retrying once reading the motor state to capture timeouts
* Avoid pulse guiding while slewing or parking
* 50ms delay after pulse guiding command to avoid device flooding
Additionally, the tracking speed NONE is removed which overrode the CUSTOM speed button. Meanwhile, the CUSTOM speed is only present if the mount supports custom tracking speeds - which is not the case for Avalon StarGO.
> Stargo 1.7 | improvements to avoid timeouts

- indi-asi/asi_focuser.cpp
- indi-asi/asi_focuser.h
ZWO has released couple of updated firmwares for EAF and I wanted to know which one mine had so added that :)
> Add EAF firmware version info

- indi-sx/sxccdusb.cpp
This increases the bulk timeout in the SX driver so that the older SXV-M25C is able to download a unbinned image from the camera. This older model is slower than the SXVR-M25C and takes 14 seconds to transfer. The older timeout was 10 seconds, this PR changes it to 20 seconds.
Link below is discussion on the issue.
https://indilib.org/forum/ccds-dslrs/5767-failure-to-take-exposure-with-starlight-sxvr-m25c.html
It gets identified as the new SXVR-M25C because it has the same USB id. It appears to work fine that way except for the timeout.
> Increase bulk timeout in SX driver to support older SXV-M25C 

- debian/indi-avalon/changelog
- indi-avalon/CMakeLists.txt
- indi-avalon/lx200stargo.cpp
- indi-avalon/lx200stargo.h
In rare cases, StarGO gets overflooded with too many commands in a row. This could lead to the situation, that StarGO hangs completely and does not react any more on new commands.
To avoid this, a configurable delay is added between two mount commands. It's set to 50ms as standard, but can be changed individually, if this value turns out to be inappropriate.
> StarGO 1.8 | Configurable delay between mount commands

- CMakeLists.txt
Now that SBIG 64 bit is possible, the restriction on aarch64 for SBIG can be removed.
> Removing aarch64 restriction

- debian/indi-sx/changelog
- indi-sx/sxccd.cpp
- indi-sx/sxccd.h
- indi-sx/sxconfig.h
- Added switch to specify whether camera has a Bayer filter or not.
- Enable Bayer-related text fields when Bayer filter selected.
- Update minor version number.
> Added Bayer filter support for color cameras

- indi-duino/devices/Firmwares/indiduinoMETEO/indiduinoMETEO.ino
- indi-duino/devices/meteostation_sk.xml
The Arduino based INDI weather driver has it's own style defining the property names. With this change, all sensor parameters obtain the prefix WEATHER_, similar to other INDI weather drivers.
This makes it possible using this INDI weather driver in the EKOS Observatory module to display the weather data there.
Additionally, a weakness has been eliminated for the cases that there is no IR radiance sensor present, which created compile problems on Arduino.
> Induino weather name standards

- indi-gpsd/gps_driver.cpp
GPSD 3.20 has changed type of time in gps_fix_t and renamed a function so use conditionals to select either one.  Tested to compile with 3.17 (in Ubuntu 19.10 and Raspbian Buster) and 3.20 (in Ubuntu 20.04).
> GPSD 3.20 compile fix

- indi-eqmod/eqmodbase.cpp
- indi-eqmod/scope-limits/scope-limits.cpp
- indi-eqmod/scope-limits/scope-limits.h
This is a proposal for saving the configuration items "Abort tracking", "Abort slewing" and "Abort Goto" in the context of horizon management. Saving configuration now includes those items.
As for other drivers, configuration should never be saved when the device is not connected, as undefined properties won't be part of the saved data stream. Properties not saved because they are undefined revert to their default value on next load.
Tested with simulation mode, loading/saving, connecting/disconnecting.
> Save horizon configuration items.

- debian/indi-avalon/changelog
- indi-avalon/CMakeLists.txt
- indi-avalon/lx200stargo.cpp
- indi-avalon/lx200stargo.h
- indi-avalon/lx200stargofocuser.cpp
- indi-avalon/lx200stargofocuser.h
- indi-sx/sxconfig.h
Avalon StarGO has the feature to adjust the tracking speed in the range of +/- 5%. This release adds a control to the RA/DEC tab to set the value.
Additionally, this release holds some bug fixes and code cleanup.
> Stargo 1.9 | Tracking adjustment

- debian/indi-avalon/changelog
- indi-avalon/CMakeLists.txt
- indi-avalon/lx200stargo.cpp
- indi-avalon/lx200stargo.h
The tracking adjustment released with 1.9 has been updated so that the configured value is directly stored in the firmware and no longer in the INDI server configuration.
> Stargo 1.10 | Tracking adjustment stored permanently

- indi-eqmod/eqmodbase.cpp
- indi-eqmod/eqmodbase.h
- indi-eqmod/indi_eqmod_sk.xml
- indi-eqmod/simulator/skywatcher-simulator.cpp
- indi-eqmod/skywatcher.cpp
- indi-eqmod/skywatcher.h
This fixes the issue #39 and besides adds support for EQ6-R Pro mount.
- adds one or two snap port switches in the options tab depending on the mount model (hardcoded in HasSnapPort functions)
- adds EQ6-R Pro mount model with code 0x23 (with a built-in USB port)
> indi-eqmod: Implement Snapport control 

- indi-eqmod/eqmodbase.cpp
- indi-eqmod/skywatcher.cpp
- indi-eqmod/skywatcher.h
The commit https://github.com/indilib/indi-3rdparty/commit/9379f0b7e5e7159a4c70fbec37a1bbe56ed663de made for issue https://github.com/indilib/indi-3rdparty/issues/70 introduced an error for mounts not supporting polar scope led control.
- Added an exception handler around the `dispatch_command` used to set led brightness
- Use the getFeatureCmd at mount initialization to state if the mount model has support for polar scope led control
This has been tested on EQ6-R Pro (with polar scope led control) and AZ-EQ5 (no polar scope).
> indi-eqmod: check if mount supports led brightness control

- indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.cpp
Replace the old stale code inside isWetRain() with a simple call to
checkParameterState("WEATHER_RAIN")
and restore the original behaviour of the heating controller.
> aag_cloudwatcher_ng: fix isWetRain(), use checkParameterState()

- indi-asi/asi_ccd.cpp
During the last second the exposure updates were send in 10ms intervals. This does not make sense for any GUI. I raised this value to  100ms, which is still fast enough.
> Increase time delay for sending exposure updates

- indi-astrolink4/indi_astrolink4.xml.cmake
Hi,
I was using the astrolink4 driver from its original repository for a few weeks now and had no problem with it. I then installed the "official" driver package since it was recently integrated into the indi-3rdparty repository. Since then, the driver refused to load.
If using Kstars or INDI Web Manager interface to select the "AstroLink 4" driver from the available driver list, the driver refuse to start.
> 2020-04-26T20:01:25: Driver astrolink4: 2020-04-26T20:01:25: Driver astrolink4: execlp: No such file or directory
If however I use INDI Web Manager to explicitly add the `indi_astrolink4` driver, it works fine.
I'm not familiar with INDI driver development, but changing the xml as this PR does has allowed me to choose the driver using either Kstars or INDI Web Manager interfaces. …
> Fix astrolink4 driver declaration

- indi-duino/devices/Firmwares/StandardFirmata/StandardFirmata.ino
- indi-duino/devices/roof_sk.xml
- indi-duino/indi_duino.xml.cmake
- indi-duino/indiduino.cpp
- indi-duino/indiduino.h
Correction of a few flaws and addition of a simple "roof" interface.
1. "Lights" and "Switches" didn't persist in Timeloop (TimerHit). They
always fell back to "idle". Now the state is reflected correctly.
2. The states of the pins of Arduino weren't queried upon connection. A
small patch from the year 2014 (Ver.2.4.0 beta) is added to the orginal
StandardFirmata.ino. Now if a digital port or an analog pin is enabled,
its value is immediately sent to the client when the driver connects.
3. A simlpe "roof" is added to show how to deploy additional switches.
> Indi-duino driver revamped

- debian/indi-aok/changelog
- indi-aok/ChangeLog
- indi-aok/lx200aok.cpp
- indi-aok/lx200aok.h
This is the thoroughly tested AOK Skywalker driver at our observatory in the last few months. It behaves quit well, so I think it's time for an update.
0.9 -> 1.0
Cleared up the handling of notification of mountlock & trackstate and
added query of mount when connecting, so mountlock and trackstate is
always reflected correctly on start or reconnect.
There are some changes in the UI as well, so [here](https://github.com/indilib/indi-3rdparty/files/4559845/indi_aok.zip.zip) is the updated manual including the new screenshots.
> Productive version 1.0 of AOK Skywalker

- indi-toupbase/indi_toupbase.cpp
- indi-toupbase/indi_toupbase.h
To improve support for Altair Hypercams I have implemented BlackLevel and aligned the handling of Low and High conversion gain consistent with the way other camera manufactures like ZWO do this.
HCG adds an additional gain to the readout. In the case of an IMX294 this is a factor 4.5. The common approach is to have one continuous gain scale of which the upper limit is the in the case of the example 4.5 times higher than the native sensor upper limit. The switch over happens at the HCG threshold and the driver now calculates the sensor gain to be applied. When the LCG/HCG ratio parameter is changed it is now required to update the range of the gain parameter. [This](https://nighttime-imaging.eu/docs/develop/site/troubleshooting/altair_dualgain/) link provides some more background …
> BlackLevel and continuous gain scale for LCG/HCG

- debian/indi-pentax/control
Guess aarch64 was the wrong keyword for this?  Or it could be I'm doing it wrong...
> Exclude libricohcamerasdk dependency from arm64 builds

- debian/libatik/changelog
- debian/libatik/copyright
- indi-atik/atik_ccd.cpp
- libatik/AtikCameras.h
- libatik/CMakeLists.txt
This PR updates the Atik SDK to version 2020.06.23 (Atik now uses the release date as version).
Changelog: https://www.atik-cameras.com/change-log/
- Fixed the Horizon dark banding issue.
Note the last argument of `ArtemisCameraSpecificOptionsGetData` is now a reference instead of a pointer.
> Update Atik SDK to v2020.06.23.

- indi-atik/CMakeLists.txt
- indi-atik/atik_ccd.cpp
- indi-atik/atik_ccd.h
This PR brings support for the following features of Atik CMOS cameras:
- Even Illumination: clears the sensor buffers before exposing, avoids gradient artifacts at the expense of some read noise.
- Exposure Speed: allows choosing between PowerSave (lowest noise) and Normal buffer reading.
- Gain/Offset Presets: allows choosing between Custom, LowGain, MediumGain and HighGain gain/offset presets.
- Pad Data: shift pixel values by 4 bits so that the full dynamic range spans [0,65535] instead of [0,4095].
Note that some properties are stored in the camera itself, and will still be configured after a hardware power cycle. There is no known way to reset the hardware to defaults.
You would want Even Illumination enabled to avoid gradients, especially when doing short exposures (flats for …
> Support for Atik CMOS camera features

- indi-gpsd/gps_driver.cpp
Empty the buffer of gpsd daemon and keep just last segment of data. Fix suggested by @rtlprmft in https://github.com/indilib/indi-3rdparty/issues/180
> Fix data pile-up in gpsd

- indi-gpsd/gps_driver.cpp
- indi-gpsd/gps_driver.h
This allows to have coordinates without exchanging the driver even though the GPS is not connected
> Adding Simulation Capabilities to gpsd

- indi-gpsd/gps_driver.cpp
Attempted quick fix for issue #187. This will certainly require some testing (don't have a laptop GPS yet, so can't really test this).
> Add conditionnals to detect gpsd API version

- debian/indi-asi/changelog
- indi-asi/CMakeLists.txt
- indi-asi/asi_ccd.cpp
- indi-asi/asi_ccd.h
CMOS is normally reset just before every exposure. But sometimes residual charge may remain
and pollute new image. Running dummy short exposures just before starting a real one is found
to help in some situations. For example, it reduces ghosts of stars after dithering.
Disabled by default, user may choose to blink any number of times.
Validated on my ASI294MC Pro. Each blink takes about 300-400ms of extra time.
See extensive discussion here: https://www.cloudynights.com/topic/662887-not-rbi-on-cmos-but-this-looks-similar/
> Optionally clear CMOS before exposure

- indi-gpsd/gps_driver.cpp
Previous fix was totally bogus as it just dereferenced an uninitialized pointer.
> Correct fix status check for new gpsd

- indi-pentax/README.md
- indi-pentax/pktriggercord_ccd.cpp
- Fixed problems with shutter speeds of less than a second
- Block shutter speeds of less than a second in bulb mode to prevent hanging the camera
- Defined a valid minimum shutter speed, which prevents problems with Bias frames in Ekos
- README updated and other minor fixes
> Pentax shutter speed fixes

- indi-gphoto/gphoto_driver.cpp
Libgphoto2 does not support bulb mode on Fuji cameras. As of versions 2.5.25 fixed shutterspeed >60s are reportet in minutes (1m, 2m, 4m etc.).
The 'm' postfix ist just ignored by indi_gphoto_ccd. This is fixed in this patch.
I've sucessfully tested it on my X-T2 with exposure times up to 15 minutes.
> FIX: Parse correctly Fuji shutterspeed given in minutes.

- indi-dsi/DsiDeviceFactory.cpp
This change was made to support a camera that had the CCD name programmed incorrectly. This was debugged in [this thread](https://www.indilib.org/forum/ccds-dslrs/6570-driver-for-old-meade-dsi-1-pro.html?start=0)
> Check DSI camera name to determine model for DSI Pro

- indi-eqmod/indi_eqmod_sk.xml
- indi-eqmod/skywatcher.cpp
Adds Azgti snap port control  -- Not tested on real hardware  (indilib/indi issue #1181)
Displays Mount information code to avoid users search in serial logs (for new models)
> Azgti snap

- debian/indi-sv305/changelog
- indi-sv305/CMakeLists.txt
- indi-sv305/README
- indi-sv305/sv305_ccd.cpp
Hello,
Sarwar did the trick.
The "gain setting" issue is fixed.
Waiting a bit and triggering a first "blank" frame avoid the gain setting error.
Best regards,
Blaise
> Fixe for the SDK gain setting issue

- debian/indi-sv305/changelog
- indi-sv305/CMakeLists.txt
- indi-sv305/README
- indi-sv305/sv305_ccd.cpp
Hello,
The SV305 PRO detection is fixed.
The camera is now able to guide using the ST4 port.
Best regards,
Blaise
> SV305PRO detection fixed

- indi-asi/asi_ccd.cpp
Hi!
I am getting to know the library and I made a few simplifications.
- Using std::unordered_map
- Using foreach instead of for
- Replacing a function in a simulation
- Changing the names of cameras in the simulation.
- Using the std::swap function
Regards
Pawel
> asi_ccd/refactoring - using std containers

- indi-asi/asi_ccd.cpp
- indi-asi/asi_ccd.h
More fixes for C++.
In short, using std containers.
Regards,
Pawel
> asi_ccd/refactoring

- indi-aok/lx200aok.cpp
- indi-aok/lx200aok.h
- indi-avalon/lx200stargo.cpp
- indi-avalon/lx200stargo.h
This goes with https://github.com/indilib/indi/pull/1296 # use d m s.f with f being tenths for LX200_GEO_LONGER_FORMAT
> follow the split of LX200Format into EquatorialFormat and GeographicFormat in indilib core PR1296

- cmake_modules/FindINDI.cmake
- indi-rpicam/TODO
If libindi is compiled and installed to a non-standard path, just setting INDI_ROOT
is not enough and cmake will not find correct files from that installation without
this extra path.
> Added extra paths for finding header files.

- indi-avalon/lx200stargo.cpp
In line with common usage, alter: 
GUIDING_SPEED to GUIDE_RATE
GUIDING_SPEED_RA to GUIDE_RATE_WE
GUIDING_SPEED_DE to GUIDE_RATE_NS
Tested with PHD2 which reads guide rates from mount
Checked logs and verified that correct commands are still issued to mount and accepted
> Standardise on GUIDE_RATE

- indi-dsi/dsi_ccd.cpp
This PR fixes the Bayer pattern property configuration, which was constrained by a DSI property which did not exist at that time.
The property is now set when the device is successfully connected to.
> Fix regression on Bayer pattern property for DSI sensors.

- indi-qhy/qhy_ccd.cpp
- indi-qhy/qhy_ccd.h
This change adds previously missing camera re-initialization after read mode changes and new support for capturing overscan areas of the imaging sensor
> Read mode and overscan area support for qhy cameras

- indi-eqmod/skywatcher.cpp
Added Star Adventurer mount code (0x0A) to eqmod driver, and updated HasSnapPort1() appropriately.
Tested with my Star Adventurer 2i.
> Added Star Adventurer (mount code 0x0A - 1 snap port)

- indi-gpsd/gps_driver.cpp
This works against `gpsd` v3.22. I've not got a system setup to try with an earlier version of `gpsd`.  I know that `gpsd` v3.21 has a major version of 10, which would be able to test the else-if directive not sure of a version that is less than major version 10.
> Fix indi gps not getting fix. fixes #324

- indi-asi/asi_ccd.cpp
I got some crashes on stopping streaming with 1sec exposure.
I think this change fixes it.
> Fix race in ASICCD::StopStreaming

- indi-asi/asi_wheel.cpp
- indi-asi/asi_wheel.h
Adding the ability to calibrate the ZWO EFW
Have tested this with my own EFW, it does run the calibration, though the calibration is an async process so the call to the `libasi` call just returns success. From the sound of the EFW the calibration takes 10-15 secs (the ZWO docs say it could take 60 secs), might have to check if the status of the EFW to see if it's moving and only after it has stopped that I could say that the calibration is done.
The motivation for this change was that I need to calibrate the EFW but didn't have a windows machine to setup the ASCOM driver to run the calibration.  I used the `gpsd` refresh functionality as a basis for what was needed to allow this functionality.
> Allow calibrating of ZWO EFW

- indi-pentax/pentax_ccd.cpp
The LOGF_ERROR macro is using the `INDI::Logger::print()` function through the DEBUGF macro. `print()` expects a `char *` as message (see [indilogger.h](https://github.com/indilib/indi/blob/91bcd531c4631805d24d38343692fb8acf8fff6a/libs/indibase/indilogger.h#L250))
Right now this leads me to : `pentax_ccd.cpp:532: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char>') through variadic method; call will abort at runtime`
Using c_str() fixes this.
> LOGF_ERROR macro is expecting a char* but receiving an std::string

- indi-qhy/CMakeLists.txt
- indi-qhy/qhy_ccd.cpp
- indi-qhy/qhy_ccd.h
- indi-qhy/qhy_ccd_test.cpp
- indi-qhy/qhy_fw.cpp
- indi-qhy/qhy_fw.h
- indi-qhy/qhy_video_test.cpp
This PR includes enhancements for QHYCCD read mode ans streaming mode support.
qyh_ccd.cpp
* Query the camera for available read modes only once during initial QHYCCD::connect() and maintain read mode information in new struct QHYReadModeInfo.
* Maintain the current read mode state in memory and call InitQHYCCD() only after the requested read mode changes from the currently set read mode. Before the camera was re-initialized also after the user set re-applied the read mode setting the camera currently is in.
*  Maintain the current streaming mode state in memory and Call InitQHYCCD() whenever camera goes into a new streaming mode change.
* Style fixes as per INDI AStyle configuration
qhy_ccd.h
* Add new variables to support the internal tracking of read mode and streaming mode states
* …
> Indi qhy streaming work

- indi-celestronaux/celestronaux.cpp
Wen the object goes to alt encoder < 0 the tracking wraps around in GetAlt function and results in fast swing in Alt to the other side of the sphere.
> URGENT: Fix Alt < 0 wraparound in tracking (Dangerous!)

- debian/indi-asi-power/changelog
- indi-asi-power/CMakeLists.txt
- indi-asi-power/Changelog
- indi-asi-power/asipower.cpp
- indi-asi-power/asipower.h
Control the DSLR shutter port on GPIO 21. Allows setting exposure, count and delay. Accurate timing to within about 1ms or so.
Arbitrary limit on exposures to 3600s.
> indi-asi-power Add DSLR control

- indi-qhy/qhy_ccd.cpp
Hi!
The `#include <map>` was removed from streammanager.h in PR https://github.com/indilib/indi/pull/1383.
This causes a compilation error of qhy_ccd.cpp.
I have added a header file to a source file that uses std::map.
> Add missing include

- indi-asi/asi_ccd.cpp
- indi-asi/asi_ccd.h
- indi-asi/asi_helpers.h
- indi-asi/singleworker_tmp.h
Hi!
Improving the readability of the driver.
https://github.com/indilib/indi/pull/1389 is required for this PR.
Changes:
- Use INDI::Property.
- Use INDI::Timer, INDI::ElapsedTimer.
- Use SingleWorker for Exposure/StreamVideo.
- Add more ASI_ERROR_CODE checks.
- Unified nomenclature.
- Add string code error.
- Hotplug cameras - no driver restart needed.
> Refactoring - ASI CCD driver

- debian/indi-rpi-gpio/changelog
- indi-rpi-gpio/CMakeLists.txt
- indi-rpi-gpio/Changelog
- indi-rpi-gpio/README.md
- indi-rpi-gpio/rpigpio.cpp
- indi-rpi-gpio/rpigpio.h
Allos GPIO to be specified as Active Low so switching on changes pin value to 0 rather than 1. 
Someties GPIO use active low e.g. when operating relays
Applies to on/off, PWM and timed pins
> indi-rpi-gpio v0.3 Add Active Low option

- libfishcamp/fishcamp.c
Bugfix allows builds on older systems.
> Bugfix typos - fishcamp

- indi-eqmod/skywatcher.cpp
Resolves #358 
(I've made this PR using my @beaglebot github account, rather than the @bengal123 account I used in the issue earlier)
A number of EQMOD users reported that the PHD2 star cross test was failing, and the PHD Guiding Assistant would incorrectly report large DE backlash values (mine was 22000ms). The following message was present in the EQMOD log when these errors occured:
```
"[WARNING] Warning: Invalid parameter -> Can not change rate while motor is running (direction differs). "
```
The error was triggered when a guide north command was quickly followed by a guide south command (within 1 second). This is unlikely to happen in a normal guiding situation, but does happen during the cross test and backlash estimation.
There's a test harness which duplicates the bug …
> Fix for "Can not change rate while motor is running (direction differs)" error when guiding

- libfli/CMakeLists.txt
I tried to compile this package on openSUSE, but it failed due to undef reference.
Looking at the CMakeFileLists.txt, it seems that the file is missing `-lpthread`.
Once this was added, compilation went fine.
> Add missing pthread lib to libfli/CMakeLists.txt

- debian/indi-asi-power/changelog
- debian/indi-rpi-gpio/changelog
- debian/libpigpiod/changelog
- indi-asi-power/CMakeLists.txt
- indi-asi-power/Changelog
- indi-asi-power/README.md
- indi-asi-power/asipower.cpp
- indi-asi-power/asipower.h
- indi-rpi-gpio/CMakeLists.txt
- indi-rpi-gpio/Changelog
- indi-rpi-gpio/README.md
- indi-rpi-gpio/rpigpio.cpp
- indi-rpi-gpio/rpigpio.h
- libpigpiod/CMakeLists.txt
- libpigpiod/README.md
- libpigpiod/pigpiod.service.in
Add -m option when starting pigpiod to reduce idle CPU usage
Replace the pigpio timer in indi-asi-power and indi-rpi-gpio with the built in INDI timer as the pigpio timer does not work with the -m option.
> Replace pigpio timer with INDI timer

- debian/indi-aok/changelog
- indi-aok/CMakeLists.txt
- indi-aok/ChangeLog
- indi-aok/lx200aok.cpp
The 'Use PulseCmd'-switch is removed as it makes definitively no sense **not** to use the built-in pulse commands of the skywalker controller (TCS).
Reason 1: The switch leads to confusion and off-setting can easily be overseen.
Reason 2: Switching 'Use PulseCmd" off, i.e. using the emulated pulse commands functions like in the lx200telescope driver, produces an extremely bad guiding due to timer lags.
> Removed the 'Use PulseCmd'-switch

- indi-asi/asi_ccd.cpp
ZWO ASI cameras 120MM (USB 2.0) sometimes/frequently fails taking
exposures when set in 16-Bit mode. To overcome this problem
a 'hack' is proposed to switch to 8-Bit mode. The
ZWO ASI cameras 130MM suffers by the same problem, thus apply
the 'hack' also to this camera.
> Apply 8-bit video hack also for older ASI 130MM (USB 2.0)

- indi-aok/lx200aok.cpp
We have to delete this property before defining the new ones. Otherwise
we break the list of buttons defined beforehand and lose their
responsiveness in the INDI Control Panel when called from EKOS
> Correction concerning the removal of the UsePulseCmd-Switch (#395):

- indi-qhy/qhy_ccd.cpp
- indi-qhy/qhy_ccd.h
add support for reading humidity sensor, if supported.
tested with qhy268m:
rsarwar@astroberry : ~/workspace/indi-3rdparty-branch/indi-qhy/cbuild
$ indiserver ./indi_qhy_ccd 
2021-06-24T16:01:37: startup: indiserver ./indi_qhy_ccd 
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: -- InitQHYCCDResource param
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: QHYCCD|QHYCCD.CPP|InitQHYCCDResource()|START
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: QHYCCD|QHYCCD.CPP|InitQHYCCDResource|auto_detect_camera:false,call InitQHYCCDResourceInside
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: QHYCCD|QHYCCD.CPP|InitQHYCCDResourceInside|START
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: QHYCCD|QHYCCD.CPP|libusb_version 1.0.22.11312
2021-06-24T16:01:37: Driver ./indi_qhy_ccd: …
> indi-qhy: add support for qhy humidity readout

- indi-bresserexos2/BresserExosIIGoToDriver.cpp
- indi-bresserexos2/CMakeLists.txt
- indi-bresserexos2/Documentation/FAQ.md
- indi-bresserexos2/Documentation/Troubleshooting.md
- indi-bresserexos2/README.md
- indi-bresserexos2/SerialCommand.cpp
- indi-bresserexos2/SerialCommand.hpp
Errors were made and fixed in time and location handling. 
This PR fixes: 
- 360° complement longitude handling for negative (westward) values.
- libnova now handles time and zone handling and should no longer provide wrong times to the handbox.
> Indi bresserexos2 v900 hotfix

- debian/libpigpiod/postinst
This resolves issue related to installing libpigpiod on systems that do not boot with systemd e.g. dockerized system
> Handle non-systemd systems. Fixes #440

- indi-toupbase/oem_cameras.cpp
There was a bug in the original change that added the OEM camera support. Apparently I was getting lucky with the port that I was plugging my camera into.
> fix toupcam OEM bus id

- indi-asi/asi_base.cpp
Hi Jasem,
based on our discussion on INDI forum, I cleaned up the VERBOSE_EXPOSURE time as constant and adjusted the sending of CCD_EXPOSURE = 0 only if the exposure is finished. The solution is used in the QHY driver as well, which also only reports CCD_EXPOSURE back if timeLeft is bigger than 0.0049 s. Both driver set the CCD_EPOSURE value to 0 explicit anyway if exposure is finished.
I cannot build myself, so please review an accept if ok or comment if wrong.
Michel
> Adopt ASI driver to simulator behavior and like QHY driver

- indi-aok/lx200aok.cpp
Don't know why, but a small correction for lunar tracking slipped away in the PR of yesterday.
> Driver Version 2.0 (small addendum for lunar tracking mode)

- indi-avalon/lx200stargo.cpp
getTrackingAdjustment currently treats values from the device as octal but they should be decimal.
Change sscanf format from i to d to return a decimal value
> Fix getTrackingAdjustment sscanf format to return decimal value

- indi-celestronaux/CMakeLists.txt
- indi-celestronaux/auxproto.cpp
- indi-celestronaux/auxproto.h
- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/celestronaux.h
- indi-celestronaux/indi_celestronaux.xml.cmake
- indi-celestronaux/simulator/nse_telescope.py
This is a large refactor for the INDI Celestron AUX driver:
+ Add Track modes.
+ Add Track rates.
+ Fix parking/unparking.
+ Add PID control loop.
+ Support for both Alt-Az and Equatorial mounts (EQ mounts not well tested).
+ Migrate to new INDI styled properties.
+ Add new mount types in XML for selection.
+ Add raw mount information and angle transformations.
+ Improve documentation.
I just had one chance to test it tonight before the clouds rolled in. Tracking is OK. 30 seconds exposures are OK, sometimes star trails. The PID algorithm could be improved.
> DRAFT: Celestron aux refactor

- indi-dsi/indi-dsi.spec
- libapogee/libapogee.spec
indi-dsi: https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/build/3154582/
libapogee: https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/build/3154802/
> udev_spec_fix: fix some udev spec file entries that were missed

- indi-duino/CMakeLists.txt
On Linux it appears libfirmata is a static library, but it is installing as a dynamic library on MacOS.  As such, we need to install the dynamic library, not leave it in the build folder.
> Fixing Mac Installation problem for libfirmata

- indi-celestronaux/auxproto.h
When compiling `indi-celestronaux` version 1.8.4 I got the following error message:
```
In file included from /var/tmp/portage/sci-libs/indilib-driver-celestronaux-1.9.4/work/indi-3rdparty-1.9.4/indi-celestronaux/auxproto.cpp:24:
/var/tmp/portage/sci-libs/indilib-driver-celestronaux-1.9.4/work/indi-3rdparty-1.9.4/indi-celestronaux/auxproto.h:120:9: error: ‘size_t’ does not name a type
120 |         size_t dataSize() const
|         ^~~~~~
```
This patch adds the necessary header file, so the type `size_t` is known to the compiler.
* Operating System: Linux
* Distribution: Gentoo
* Compiler: GCC 11.2.0
> celestronaux: add missing header file

- libapogee/LICENSE
- libapogee/parseCfgTabDelim.cpp
As noted in #521 I've updated the license text with the one available from gnu.org website.
I've also pushed a change to fix libapogee build with GCC 12 (just landed in Fedora Linux).
> Fix libapogee license and build with GCC 12

- indi-gphoto/gphoto_ccd.cpp
S_IRUSR is a valid "mode" parameter for O_CREAT and O_TMPFILE.
S_IRUSR is not a valid "flags" parameter, and in addition to being
wrong it is architecture dependent which flag happens to have the
same value.
@knro This was introduced by commit aa3d611039728f4702ecbd477e35bcd39f3eb710.
> indi-gphoto: Fix open() call

- libfishcamp/CMakeLists.txt
- libsbig/CMakeLists.txt
Also reformat libfishcamp CMakeLists
This fix #547 
Attached cmake_install file pre and post fix where it can be seen the fix working
[cmake_install-post.txt](https://github.com/indilib/indi-3rdparty/files/8110323/cmake_install-post.txt)
[cmake_install-post-libfishcamp.txt](https://github.com/indilib/indi-3rdparty/files/8110324/cmake_install-post-libfishcamp.txt)
[cmake_install-pre.txt](https://github.com/indilib/indi-3rdparty/files/8110325/cmake_install-pre.txt)
[cmake_install-pre-libfishcamp.txt](https://github.com/indilib/indi-3rdparty/files/8110326/cmake_install-pre-libfishcamp.txt)
> Fix properly override of FIRMWARE_INSTALL_DIR

- libasi/CMakeLists.txt
Latest version is 1.21, not 1.21.3 (https://astronomy-imaging-camera.com/software-drivers)
> Fix ASICamera version

- indi-astromechfoc/astromech_focuser.cpp
I was unable to get a 400mm f/2.8 III on a Lens Controller Mark II
to span its entire focus range with the default settings.
With the range [0,32767] it appears to span the whole range, though
it's hard to be sure if the lens is going as far beyond infinity as
lens supports.  Sending 32768 or a higher value to the device makes
it start reporting a negative position number,  so I am pretty sure
that is too far.
> Change maximum position for astromechfoc from 9999 to 32767.

- indi-webcam/CMakeLists.txt
When compiling `indi-webcam` version 1.9.5 I got the following error message:
```
[1/2] /usr/bin/x86_64-pc-linux-gnu-g++  -I/var/tmp/portage/sci-libs/indilib-driver-webcam-1.9.5/work/indi-3rdparty-1.9.5/indi-webcam_build -I/var/tmp/portage/sci-libs/indilib-driver-webcam-1.9.5/work/indi-3rdparty-1.9.5/indi-webcam -I/usr/include/libindi  -g -std=c++0x -O2 -pipe -Wno-deprecated-declarations -MD -MT CMakeFiles/indi_webcam_ccd.dir/indi_webcam.cpp.o -MF CMakeFiles/indi_webcam_ccd.dir/indi_webcam.cpp.o.d -o CMakeFiles/indi_webcam_ccd.dir/indi_webcam.cpp.o -c /var/tmp/portage/sci-libs/indilib-driver-webcam-1.9.5/work/indi-3rdparty-1.9.5/indi-webcam/indi_webcam.cpp
FAILED: CMakeFiles/indi_webcam_ccd.dir/indi_webcam.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ …
```
> webcam: fix build failure

- indi-eqmod/skywatcher.cpp
- indi-eqmod/skywatcher.h
This PR reduces the amount of time `indi_eqmod_telescope` waits for the mount to answer on the serial port.
The original timeout was 5 seconds, which is high enough to cause safety issues when moving at a high slew rate, and causes spikes difficult to explain while guiding.
Obviously, there should not be any serial communication issues for the mount to operate safely. However, it may happen that transient errors appear when oxydisation weakens cable connections, or causes a capacitive effect on the RX line which smoothens voltage changes.
Serial communication at 9600 bauds roughly translates to 960 payload bytes per second, and `eqmod` communication is less than 10 bytes per payload. Roughly 11 milliseconds are needed for a payload to be read, neglecting firmware processing time.
The …
> indi-eqmod: recover transient error after 200ms, retry 75 times.

- indi-atik/CMakeLists.txt
- indi-atik/atik_ccd.cpp
- indi-atik/atik_wheel.cpp
- libatik/AtikCameras.h
- libatik/CMakeLists.txt
This PR imports the Atik SDK 2021.11.02.862.
DLL v2021.11.02.862
Fixed issue where our CMOS cameras (ACIS/Horizon/Apx) would always report PowerSave as their exposure speed.
DLL v2021.10.22.847
Fixed error with “ArtemisHotPixelAdvancedCalculcationComplete” renamed “ArtemisHotPixelAdvancedCalculationComplete”
Updated the C++ example to include the latest revision of AtikCameras.h & AtikCameras.cpp
DLL v2021.10.18.840
Added 4 new functions to the API:
ArtemisHotPixelAutoRemoval
ArtemisHotPixelAdvancedRemoval
ArtemisHotPixelAdvancedStartCalculateHotPixels
ArtemisHotPixelAdvancedCalculcationComplete
Mac build no longer statically links to libusb
First stable build containing Apx60 Code
Setting the camera’s exposure speed to ‘Fast’ for the moment sets the camera speed internally to ‘Normal’ …
> Import Atik SDK 2021.11.02.862, move to driver release 2.2.10.

- indi-toupbase/indi_toupbase.cpp
- indi-toupbase/indi_toupbase.h
The new feature will allow the user to select two different binning modes: "add "or "average" in the INDI control panel 
A new control is added to the Image Control Tab.
I have already presented this work in the INDI Forum. So I want to start my first pull request.
[https://indilib.org/forum/ccds-dslrs/11690-touptek-camera-binning-mode-option-average-add.html](url)
The new feature will allow the user to select two different binning modes add or average in the INDI control panel.
A new control is added to the Image Control Tab.
This feature is offered by the touptek cameras and is documented in the Touptek SDK Documentation
Please note that this is my first pull request to this project. The coding may not follow all the best practices for this project.  
I have tested with a Touptek IMX …
> New Feature for Touptek Indi Driver: Binning average/add option

- indi-sbig/sbig_ccd.cpp
- indi-sbig/sbig_ccd.h
The SBIG ST-7/8/etc cameras can be used as detectors for the SBIG self-guided spectrograph. Therefore other binning modes with different horizontal and vertical binning are supported by these devices. With this patch all supported binning modes become available.
Currently the code has only been tested with the SBIG ST-8XME. It would be necessary to test it with other SBIG devices before merging with the upstream repository.
> Enhanced binning for SBIG ST-7/8/etc cameras

- indi-mgen/mgen_device.cpp
This PR fixes the use of a deprecated function from the FTDI library v1.5 in the mgen autoguider driver.
> mgen: fix ftdi deprecation.

- indi-mgen/mgen_device.cpp
This PR attempts a different approach to manage FTDI 1.4/1.5 deprecated symbol `ftdi_usb_purge_buffers`.
> mgen: fix ftdi deprecation differently.

- indi-asi/asi_base.cpp
- indi-asi/asi_base.h
- indi-asi/asi_camera_test.cpp
- indi-asi/asi_ccd.cpp
- indi-asi/asi_ccd.h
This will allow multiple cameras of the same type to be used, and have the proper one reliably used, e.g. using the imaging ccd for imaging and the one configured for guiding used for that. Also allows more human-readable device names.
> Allow ZWO CCDs to be nicknamed, associated by the serial numbers in their firmware.

- libqhy/CMakeLists.txt
QHY firmware is being installed to /lib/firmware, and not /lib/firmware/qhy. All the udev rules point to /lib/firmware/qhy. I believe this happens because the persistent cache is being used for the variable FIRMWARE_INSTALL_DIR (the CACHE keyword), and is being overridden by previously set firmware dirs in other 3rdparty library projects. Changing it to QHY_FIRMWARE_DIR, so it has a unique name, resolves the issue.
> Fix problem where QHY firmware would get installed to the wrong directory

- indi-sv305/sv305_ccd.cpp
- Disable auto saving parameters by SVBONY Camera SDK to avoid the following problems
> In the case of the Raspberry PI, the driver may freeze the next time you try to open the camera if there is a parameter file automatically saved by the SDK.
- The fix has no impact. Parameter auto saving by SDK is unnecessary because INDI itself originally saves the configurations.
> BUGFIX: Disable auto saving parameters

- indi-sv305/sv305_ccd.cpp
- indi-sv305/sv305_ccd.h
BUGFIX: mutex life cycle to camera connection period
- Once the camera is closed and reconnected to the camera, the driver freezes without unlocking the mutex for the next camera disconnect.
- Corrected the life cycle of mutex, cond and thread of pthread from the scope of existence of Sv305CCD object to the scope of Sv305CCD::Connect to Sv305CCD::Disconnect.
- Before the correction, the state of the previous mutex was inherited at the second connection, causing a freeze on pthead_lock at the time of Disconnect.
BUGFIX: cancel streaming thread at Disconnect camera.
BUGFIX: some pthread_cond_signal was moved within the period when mutex is locked.
- pthread_cond_signal must be called during mutex lock.
BUGFIX: Fixed a case where a function exits within the mutex lock period of streamVideo.
> BUGFIX: change mutex life cycle to camera connection period and correct some pthread function calls

- indi-sv305/sv305_ccd.cpp
- indi-sv305/sv305_ccd.h
- In sv305_ccd.cpp, I implemented a process to get the ROI actually set by SVBGetROIFormat.
- After setting the ROI with SVBSetROIFormat, I need to get the actual ROI with SVBGetROIFormat, because the ROI obtained with SVBGetROIFormat may differ from the value specified with SVBSetROIFormat.
- Issue #654 was raised because this feature was not implemented.
> BUGFIX: indi_sv305_ccd: garbage data in last line (Issue #654)

- indi-eqmod/mach_gettime.cpp
- indi-eqmod/mach_gettime.h
As said on lines 4 and 6, this check is only intended for OSX.
```
/* Mac OSX prior Sierra is missing clock_gettime() */
```
Hurd also uses Mach, but does not have the same shortcomings as OSX in this area.
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
```
#ifdef __MACH__
Some applications put Apple Darwin-specific code inside #ifdef __MACH__ guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by #if defined(__MACH__) && defined(__APPLE__)
```
> Restrict overmatching MACH ifdef to only trigger on OSX and Mach

- libsv305/CMakeLists.txt
SVBONY Camera SDK v1.9.6 has been fixed a problem with SV705C RAW8 output.
> Update SVBONY Camera SDK to v1.9.6

- indi-sv305/sv305_ccd.cpp
- indi-sv305/sv305_ccd.h
- libsv305/CMakeLists.txt
- When Sv305CCD::StartExposure is executed, call SVBGetVideoData and discard any unretrieved data.
- This process avoids reading the previous data that has not been read.
> BUGFIX: indi_sv305_ccd: One previous shooting data retrieval is performed at the time of shooting. #655

- CMakeLists.txt
Missing installation of libahp-gt breaks building of indi-eqmod
Adding libahp-gt building on twice-run CMake
> Update CMakeLists.txt to fix libahp-gt installation

- CMakeLists.txt
In Fedora Linux we avoid distributing libraries and drivers which include pre-built binaries and/or firmware.
Currently we set the appropriate `--DWITH_*` flag ate build time for each component, but it would make life easier to have a global switch to exclude all components with pre-built files.
I've added such option and set it to Off, so it will not cause any change when it's not used.
> Option to disable libraries and drivers with pre built binaries

- indi-toupbase/indi_toupbase.cpp
User Denis from the INDI forum found that there is no feedback from the binning mode setting in the Touptek Indi driver.
> Binning Mode Feedback

- .github/workflows/linux.yml
- README.md
In previous versions of the Linux workflow in INDI Core it was called default.yml, now it is called linux.yml.
For this reason, the previous version of the INDI Core library was being downloaded.
> Migration to INDI Core 2.0.0 - Fix CI workflow name

- indi-eqmod/scope-limits/scope-limits.cpp
https://github.com/indilib/indi/pull/1837 The proposal to rename the timestamp function in the INDI Core library causes a temporary incompatibility with the INDI 3rd Party library. This pull request solves this problem.
> Temporarily use a copy of the timestamp function.

- debian/libahp-gt/changelog
Building DEB package libahp-gt on Debian bullseye
results first in warning:
```
dpkg-gencontrol: warning:
debian/changelog(l5): found end of file where expected more change data or trailer
```
and subsequent error:
`dpkg-deb: building package 'libahp-gt' in '../libahp-gt_1.5.8_amd64.deb'. dpkg-deb: error: unable to parse timestamp '': Success dh_builddeb: error: dpkg-deb --build debian/libahp-gt .. returned exit code 2 dh_builddeb: error: Aborting due to earlier error`
This error is due to incorrect formatted changelog. It looks like the additional space character is tolerated on Ubuntu systems, but not on Debian systems.
> Fix building DEB package on Debian systems

- indi-celestronaux/auxproto.cpp
- indi-celestronaux/auxproto.h
- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/celestronaux.h
- indi-celestronaux/simulator/nse_telescope.py
Send to AUX device 0x10 (AZM motor controller) the command 0x05 (MC_GET_MODEL) to get reply which contains the mount model version string.
The command is derived from Celestron AUXBUS Scanner https://github.com/platini2/celestronauxbus
currently the following mount versions can be inferred:
0x0001 : 'Nexstar GPS',
0x0783 : 'Nexstar SLT',
0x0b83 : '4/5SE',
0x0c82 : '6/8SE',
0x1189 : 'CPC Deluxe',
0x1283 : 'GT Series',
0x1485 : 'AVX',
0x1687 : 'Nexstar Evolution',
0x1788 : 'CGX'
In a later commit the inferred mount model can be used to properly determined whether it a a GEM, AZ_ALT or FORK mount.
> Infer from AUX command 0x05 the mount model

- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/celestronaux.h
When no HC is attached, the following three commands needs to be send to the motor controller (MC): MC_SET_POSITION, MC_SET_CORDWRAP_POSITION and MC_CORDWRAP_ON. These three commands are also send by the HC to the MC during HC startup and quick align process.
> Send AUX commands to MC imitating attached HC

- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/celestronaux.h
In the previous related commit, the hex value
data[0] = (m_MountType == EQ_GEM) ? 0x40 : 00;
was overwritten with data[0] = 0xc0 before 0x40 is sent.
In addition logging of the startupWithoutHC result is introduced.
> Fix sendingWithoutHC 0x40 0xc0 and logging

- indi-rpicam/mmalencoder.cpp
More progress in my effort to improve performance of this driver. Set the JPEG quality to 1 because we're skipping the JPEG data anyway before we extract the RAW data. This results in ~220k less data on a 2028x1520 image and is ~0.02secs quicker to process.
> indi-rpicam: Set the JPEG quality to 1 because it will be skipped anyway

- debian/libsvbony/changelog
- libsvbony/CMakeLists.txt
* Support camera SV305C
* Fix the problem that the first line and the last line of the image are incorrect when the mono camera is in 16-bit mode
* SV305C supports saturation
* Improve the frame rate of SV305C in small ROI
> updated SVBONY camera SDK to version 1.11.1

- debian/indi-svbony/changelog
- debian/libsvbony/changelog
- indi-svbony/CMakeLists.txt
- indi-svbony/doc/svbony-doc.md
- indi-svbony/svbony_ccd.h
- libsvbony/CMakeLists.txt
Change Log of libsvbony
* Support image flip
* Modify SV605CC gain setting
* Modify the gain setting of SV605CC/SV605MC
* Fix up the problem that the image cannot be obtained when the SV905C is exposed for a long time
* Remove the x86 version library in MacOS
* Fix up the problem that the last exposure image may be read in soft trigger mode
Change Log of indi-svbony
* Disabled workaround code for bug #666 "the problem that the last exposure image may be read in soft trigger mode".
> Updated SVBONY Camera SDK to Version 1.11.4

- debian/indi-svbony/changelog
- indi-svbony/CMakeLists.txt
- indi-svbony/README
- indi-svbony/svbony_ccd.cpp
- indi-svbony/svbony_ccd.h
The private variable status in the SVBONYCCD class is shared among member functions, and the value of status may be changed asynchronously by member functions running in multi-threaded mode.
In practice, the use of the status variable is closed within each member function, and there is no need to share it as a member variable. Therefore, status was changed to a local variable within the member function that uses it.
> FIXED indi-svbony: Conflict of private variables in SVBONYCCD class

- debian/indi-svbony/changelog
- indi-svbony/CMakeLists.txt
- indi-svbony/README
- indi-svbony/doc/svbony-doc.md
- indi-svbony/svbony_ccd.cpp
- indi-svbony/svbony_ccd.h
Added code to SVBONYCCD::Connect() to output the version of SVBONY Camera's firmware and SDK as information log.
This information is used when users inquire about issues.
> SVBONY CCD firmware and SDK version information logs added

- debian/indi-playerone/changelog
- indi-playerone/CMakeLists.txt
- indi-playerone/playerone_base.cpp
- indi-playerone/playerone_base.h
After 6 years with Atik 383L+ I finally upgraded my imaging camera to Player One Poseidon-M PRO. While playing around with it I noticed that setting sensor mode of the camera was not supported, which was understandable as most cameras don't have more than one, but Poseidon has two modes, low noise and normal. The SDK has nice functions to enumerate the modes and even get some description for them so adding the functionality was very straight forward.
Additionally I made some clean ups and ran through astyle which caused some diff noise to old code.
> Add sensor mode control for Player One cameras

- debian/indi-avalon/changelog
- indi-avalon/lx200stargo.cpp
Fix for a crash on MacOS when reading the park/home state.
> StarGO Release 1.13 | Bug fix for MacOS crash

- debian/indi-avalon/changelog
- indi-avalon/lx200stargo.cpp
The first fix missed a second code position that needed to be corrected.
> StarGO V 1.13.2 | Second code position needed to be corrected to fix the MacOS crash

- indi-svbony/CMakeLists.txt
- indi-svbony/svbony_base.cpp
- indi-svbony/svbony_base.h
- indi-svbony/svbony_ccd.cpp
- indi-svbony/svbony_ccd.h
- indi-svbony/svbony_helpers.h
Due to the existing SVBony bug, I rebased the ZWO driver.
> Migrate SVBony to code based on ZWO drivers

- indi-svbony/svbony_base.cpp
- indi-svbony/svbony_base.h
- indi-svbony/svbony_helpers.h
svbony_base.cpp, svbony_base.h
- SVBONYBase::grabImage disassembled and embedded in SVBONYBase::workerExposure
- Remove unused SVBONYBase::grabImage function
svbony_helpers.h
- Added processing in preparation for monochrome camera support (monochrome support not yet completed)
- Changed Luma to Luma 8 bit and Luma 16 bit
> Stabilization of SVBONYBase::workerExposure

- indi-svbony/svbony_base.cpp
- indi-svbony/svbony_base.h
- indi-svbony/svbony_helpers.h
Fixed some bugs and added workaround code for SVBONY Camera SDK
- Save default value to prevent crash(Merge with d1622b9)
- Changed the SDK to set the ROI only if it is different from the current ROI when setting the ROI.
- Added code to call SVBSetCameraMode function in SVBONYBase::Connect(). This is a workaround code for a bug in the SDK.
- Fixed parameter for setting target cooling temperature in SVB_TARGET_TEMPERATURE.
- Modified to set Bayer pattern to INDI control panel in SVBONYBase::Connect changes
SVBONY re-implementing monochrome camera
- Related modifications have been made but not yet tested with a monochrome camera (testing will be conducted after the actual equipment is obtained).
> SVBONY: Fixed some bugs and added workaround code for SVBONY Camera SDK

- debian/indi-avalon/changelog
- indi-avalon/indi_avalon.xml.cmake
Unified manufacturer name for Avalon StarGO driver in line with new AvalonUD drivers.
> Avalon StarGO V 1.13.3 | Manufacturer changed to Avalon-Instruments

- indi-asi/asi_base.cpp
Workaround for apparent ASI SDK 1.31 and 1.32 bug that exposes and gives bogus default values for GPS controls on cameras that don't have GPS and fails to complete exposures if the value is written back. More discussion on the issue in #867. Managed to reproduce and verify the fix on my ASI178MC.
> Workaround ASI SDK bogus GPS control default values

- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/celestronaux.h
The Evolution mount seems to be pretty robust to crashes (ask me how I know)- that said, it would be better not to tempt fate.
This PR implements initial slew limits.  It's sufficient to prevent tracking, an incautious goto, or a manual slew from causing too much havoc.  That said, it doesn't promise to prevent you from doing something stupid.  For example, if the mount is already beyond a limit and you (or an automation script) command it to move even further into the no-go zone, it will (at least briefly) until the next polling period.   A more robust solution that prevents all motion further into a no-go zone would be better, but this is enough to start.
Limits are set as angles relative to the index (i.e. startup position if no HC connected).
> celestron-aux: initial support for slew limits

- indi-duino/CMakeLists.txt
Ensure that the firmata library is linked statically, since it will not be installed.
> Making libfirmata library static

- CMakeLists.txt
Without this, the toupcam drivers (altair_ccd, etc...) are not built into indi-full.
> libmeadecam missing into toupcam dependencies

- indi-libcamera/README.md
Encountered build issues due to the missing libboost-program-options dependency, so I figured it may help out others if this was mentioned in some place.
> add missing build dependency to README

- debian/indi-svbony/changelog
- indi-svbony/CMakeLists.txt
- indi-svbony/README
- indi-svbony/svbony_base.cpp
- indi-svbony/svbony_base.h
ISSUE #655 regarding SVBONY Camera SDK still reproduces rarely.
The workaround code for this issue has been re-implemented.
> SVBONYCCD: Workaround for an issue that rarely retrieves the previous iamge.

- indi-qhy/CMakeLists.txt
This commit fixes the following build failure:
```
[1/8] /usr/bin/x86_64-pc-linux-gnu-g++ -DCALLBACK_MODE_SUPPORT -I/var/tmp/portage/sci-libs/indilib-driver-qhy-2.0.7/work/indi-3rdparty-2.0.7/indi-qhy_build -I/var/tmp/portage/sci-libs/indilib-driver-qhy-2.0.7/work/indi-3rdparty-2.0.7/indi-qhy -I/usr/include/libindi -I/usr/include/libqhy -I/usr/include/libusb-1.0  -march=native -O2 -pipe -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -O1 -Wa,--noexecstack  -Wall -Wextra -Wno-unused-but-set-variable -Wno-format-truncation -g -Wno-error -std=gnu++14 -fPIE -MD -MT CMakeFiles/indi_qhy_focuser.dir/qhy_focuser.cpp.o -MF CMakeFiles/indi_qhy_focuser.dir/qhy_focuser.cpp.o.d -o CMakeFiles/indi_qhy_focuser.dir/qhy_focuser.cpp.o -c /var/tmp/portage/sci-libs/indilib-driver-qhy-2.0.7/work/indi-3rdparty- …
```
> Fix build with system JSON library

- indi-asi/asi_base.cpp
Removed wildcard # in serial number label (SN vs SN#) to make ASI drivers compliant with indi-mqtt publication rules (no wildcard )
> Update asi_base.cpp -- removed #

- indi-armadillo-platypus/beaver_dome.cpp
- indi-armadillo-platypus/dragonfly_dome.cpp
- indi-maxdomeii/maxdomeii.cpp
- indi-nexdome/nex_dome.cpp
- indi-ocs/ocs.cpp
- indi-rolloffino/rolloffino.cpp
- indi-talon6/talon6.cpp
@knro , Fixed errors. It was built successfully with latest changes.
> Fix issues to build successfully

- indi-aagcloudwatcher-ng/indi_aagcloudwatcher_ng.cpp
I noticed, that my cloudwatcher was showing mutliple humidity values in the parameters tab. All are zero and kstars observatory tab was not showing humidity value. This happens, when kstars disconnects and reconnects the driver. Each time the handshake method is called, adding another parameter.
This fix simply checks if the parameter already exists before adding it.
> Fix broken humidity reading after reconnect of device

- debian/libsvbony/changelog
- libsvbony/CMakeLists.txt
Updated SVBONY Camera SDK to Version 1.12.8
Change Log of libsvbony
* Fixed the problem that the program occasionally exits abnormally under macOS
* Fixed the issue where the cooling power value obtained when cooling is turned off is greater than 0
* MaxBitDepth in SVB_CAMERA_PROPERTY returns the actual bit width of the sensor
> Libsvbony update to 1.12.8

- indi-toupbase/indi_toupwheel.cpp
TimerHit did not work because SetTimer was not called when the filter was set.
Due to this issue, the capture module cannot start capturing while waiting for the filter to be set.
> BUGFIX #944: toupcam EFW driver

- indi-toupbase/indi_toupbase.cpp
Fix TEC temperature range initialisation (missing cast, missing scaling), set 0 degree as starting point instead of indicated minimum.
> Fix TEC temperature range initialisation

- debian/indi-svbony/changelog
- indi-svbony/CMakeLists.txt
- indi-svbony/svbony_base.cpp
BUGFIX: SVBONY CCD: Stop cooling at disconnection
The INDI CCD driver did not turn off the cooling, and the cooling remained on even after disconnecting EKOS.
This issue has been fixed.
> BUGFIX: SVBONY CCD: Stop cooling at disconnection

- indi-celestronaux/CMakeLists.txt
- indi-celestronaux/celestronaux.cpp
- indi-celestronaux/simulator/nse_simulator.py
- indi-celestronaux/simulator/nse_telescope.py
- indi-gphoto/gphoto_driver.cpp
This is a first attempt to implement tracking in AltAz mode with calculated track rates and PID controlled fine-tuning. The most of the tracking is handled by Horiz<->Eq transformation. The PID is used only to correct the small drift, probably caused by from the skew in clock rates (to be verified). The test results: show RMS tracking noise below 0.1 arcsec for Alt < 80 deg. This is essentially LSB of the hardware.
> WIP: (CAUX) Implement predictive tracking with PID corrections in AltAz mode.

- indi-ahp-xc/indi_ahp_xc.cpp
- indi-mgen/mgen.h
- indi-pentax/pentax_ccd.cpp
- indi-pentax/pktriggercord_ccd.cpp
This is a tentative PR to fix out-of-bounds warnings emitted by C++14 when building indi-mgen.
The implementation restricts the set of function candidates the compiler selects from when using an initialiser list on IOBuffer: `IOBuffer{opcode,literal,literal...}`, and makes sure to allocate space before copying the list data.
@iliaplatone I considered that placeholders with their real sizes instead of 1 byte everywhere wasn't that problematic. Feel free to comment.
`calloc(sizeof,sizeof)` expects the number of items as first argument, and the size of each as second.
> fix(3rd-party): fix mgen, ahp-xc and pentax errors on fedora.

- debian/indi-svbony/changelog
This fixes timestamp formatting of debian/changelog which resulted in following debian packaging error:
`dpkg-deb: error: unable to parse timestamp '': Success`
> Fix timestamp in indi-svbony debian changelog

- indi-eqmod/skywatcher.cpp
Related to https://github.com/indilib/indi/issues/1162
I just got the CQ350, which is basically a (relatively) lightweight version of the EQ8.
I added the right mount code (0x25) so it can be recognised, plus I added the mountcode support for the autohome function.
Tested locally of course.
> Add support for CQ350 Pro

- indi-fishcamp/CMakeLists.txt
Fixes an issue of locating libusb.h during compilation on some systems
> Adding missing find_package for libusb

- indi-qhy/README
I initially got this error when trying to `cmake -DCMAKE_INSTALL_PREFIX=/usr .` in indi-qhy:
```
CMake Error at CMakeLists.txt:20 (find_package):
By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
project has asked CMake to find a package configuration file provided by
"nlohmann_json", but CMake did not find one.
Could not find a package configuration file provided by "nlohmann_json"
with any of the following names:
nlohmann_jsonConfig.cmake
nlohmann_json-config.cmake
Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
"nlohmann_json_DIR" to a directory containing one of the above files.  If
"nlohmann_json" provides a separate development package or SDK, be sure it
has been installed.
```
After running a `sudo apt install nlohmann-json3-dev`, the …
> Add nlohmann/json to list of indi-qhy dependencies

- indi-gphoto/gphoto_driver.cpp
for external shutter usage. Tested with:
- Fuji XT1 (firmware 5.52)
- RTS external shutter
- FORCE_BULB set to ON
- PR on libgphoto2 [https://github.com/gphoto/libgphoto2/pull/1079]
> indi-gphoto with external shutter

- indi-qhy/qhy_focuser.cpp
Make cmd_version_board optional for boards that don't report cmd_json["bv"]
> QHY Focuser Optional Board Version

- indi-svbony/svbony_base.cpp
Correct reversed condition in function SVBONYBase::sendImage.
> FIX_Reversed_Condition_in_Commit_fa35d75

- indi-atik/atik_ccd.cpp
- indi-atik/atik_ccd.h
This MR adds two properties to the Atik driver, `CCD_GAIN` and `CCD_OFFSET`, allowing adjustment of gain and offset in the same way as `CCD_CONTROLS[0]` and `CCD_CONTROLS[1]`. These properties should behave like those of the QHY driver.
I don't have a APX at hand, I expect the properties to work identically on Horizon, Horizon2 and APX, but I don't iknow if they will be setup properly for APX.
> feat(atik): add gain/offset control outside of CCD_CONTROLS.

- CMakeLists.txt
Removing AstroAsis from MacOS ARM builds since it has no arm library currently
> Removing AstroAsis from MacOS ARM

- indi-atik/atik_ccd.cpp
This MR fixes remaining issues with gain/offset properties in the Atik driver.
Tested OK in my observatory, with raw INDI properties and with Ekos.
> fix(atik): fix gain/offset property sync.

- libricohcamerasdk/include/ricoh_camera_sdk/camera_status.hpp
The camera_status.hpp file uses uint32_t, which is defined in the <cstdint> header.
Including this header resolves a compilation error.
> Add missing cstdint inlcude for uint32_t

- indi-rolloffino/Rolloff.ino.arduinoR4WIFI
This sketch enables a Blutezeit 1400-lb gate opener to OPEN/CLOSE with limit switches via WIFI. The WIFI address is dynamic; the PORT is 7624. //It was built with a Arduino Uno R4 WIFI and the Arduino 4-Relay Shield (bought directly from Arduino) using the NO ports attached to OPEN/CLOSE/STOP and the COMMON ports all attached to GND. //Limit switches were ME8108 from amazon utilizing NO contacts. 2 wires required/one is attached to a ground with a 10k resistor the other contact is attached to D2 (OPENED) and D3 (CLOSED) //It also enables updating sketches via Wifi... connect with the ARDUINO IDE on the SAME network with the IP address and Port.
> Sketch for Arduino R4 WIFI over WIFI

- libapogee/helpers.cpp
- libqsi/SimpleIni.h
Two functions were deprecated in C++ 17 that are causing issues when building INDI 3rdParty in Clang when switching the compiler standard from C++ 11 to C++ 17.  These include std::binary_function and std::bind2nd.  This commit should fix that.
> Fixing 2 Compile Errors in MacOS due to Deprecated Functions in C++ 17

- indi-starbook-ten/starbook_ten.cpp
Before the fix, the output was (note the spurious `-`):
ra=2.55, dec=-2.55, ra=2+33.00000&dec=-2+-33.00000
ra=2.5, dec=-2.9, ra=2+30.00000&dec=-2+-54.00000
After the fix:
ra=2.55, dec=-2.55, ?ra=2+33.00000&dec=-2+33.00000
ra=2.5, dec=-2.9, ?ra=2+30.00000&dec=-2+54.00000
The spurious `-` seems to be interpreted as then going to e.g. -4.7 when asked to go to -5.3.
Reported-by: Hans Jürgen Mayer
> starbook-ten: fix negative dec handling

- CMakeLists.txt
- indi-nightscape/nstest-main.cpp
I was using the variable CMAKE_SYSTEM_PROCESSOR to differentiate between the ARM and X86 builds on MacOS to determine which drivers to build.  This worked on my system, but not in the Craft CI build for KStars.  I think that CMAKE_OSX_ARCHITECTURES should work in the CI build as well.  Also I found a build error in a driver due to an unused variable
> Fixing the craft CI build for drivers that are not arm compatible yet.

- .github/workflows/macos.yml
Trying to fix the arm ci build on indi 3rd Party on MacOS.  While CMAKE_OSX_ARCHITECTURES gets set in craft and locally on the OS, it doesn't appear to get set in the CI build on GitHub
> Setting an environment variable for the arm ci build on MacOS

- CMakeLists.txt
Set the CMake flag to create the compile_commands.json file which allows clangd to index the project and provide code completion, and cross-referencing in advanced text editors and IDE-s. #1144
> Create compile_commands.json when running cmake

- cmake_modules/CMakeCommon.cmake
The CMakeCommon module defined wrong linking flags for shared libraries, causing linking errors in shared object files, when they were linked just like normal executable.
Applied gersemi to fix up most of cmake-lint errors in the file.
It also epcified the FORTIFY flag for debug builds resulting in excessive compile warnings due to that flag not being available in debug building.
fixes #1150
> Fix  and clean CMakeCommon module

- indi-gige/src/ArvInterface.h
I tried to compile the latest master and indi-gige fails with this error:
```
In file included from /build/indi-3rdparty/indi-gige/src/indi_gige.h:26,
from /build/indi-3rdparty/indi-gige/src/indi_gige.cpp:29:
/build/indi-3rdparty/indi-gige/src/ArvInterface.h: In constructor 'arv::ArvCamera::ArvCamera(void*)':
/build/indi-3rdparty/indi-gige/src/ArvInterface.h:76:21: error: unused parameter 'camera_device' [-Werror=unused-parameter]
```
So I marked it as maybe_unused. Not sure if this is how you'd fix it but at least with this it compiles again.
> Fix -Werror=unused-parameter
